name: "Build"

on:
  push:
    branches: [ "**" ]
    tags-ignore: [ "**" ]
  pull_request:
  workflow_dispatch:
  merge_group:

concurrency:
  cancel-in-progress: true
  group: build-${{ github.event.pull_request.number || github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and publish
    strategy:
      fail-fast: false
      matrix:
        java:
          - 21

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          check-latest: true
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - name: Setup gradle cache
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/nightly' || matrix.java != 21 }}

      - name: Execute build and tests
        run: ./gradlew build test shadowJar --stacktrace

      - name: Publish test summary
        if: ${{ github.event_name == 'push' && !startsWith(github.ref, 'refs/heads/gh-readonly-queue/') && matrix.java == 21 }}
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          junit_files: "**/build/test-results/test/TEST-*.xml"

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v8

      - name: Prepare artifact jar
        if: ${{ github.event_name == 'push' && !startsWith(github.ref, 'refs/heads/gh-readonly-queue/') && matrix.java == 21 }}
        run: cp cloudnet-rest-module/build/libs/cloudnet-rest.jar cloudnet-rest.jar

      - name: Upload artifact jar
        uses: actions/upload-artifact@v4
        if: ${{ github.event_name == 'push' && !startsWith(github.ref, 'refs/heads/gh-readonly-queue/') && matrix.java == 21 }}
        with:
          name: CloudNet-Rest
          path: cloudnet-rest.jar
